### PR TITLE
Adding an environment variable

### PR DESCRIPTION
**Pull request by tolitski**
Document how to add the environment variable where a different DVSwitch.ini file is located

### CODE REVIEW

**Comment by N4IRS** [comment]
The environment variable DVSWITCH can already points to the DVSwitch.ini file.

**Comment by tolitski** [comment]
Thank you Steve,

Looks like I misread Steve's (AWV] comment, he was referring to the service definition. This confused me as it's mentioned but not included in the sample files.

Best regards and thanks for the reply

Lito
________________________________

**Comment by N4IRS** [comment]
It will be included in the next update. It will be defined it the systemd unit for MMDVM_Bridge.

**Comment by N4IRS** [comment]
See the systemd unit file

**Pull request closed without merging**
